### ISSUE TITLE
Problem running Sc-ATAC pipeline

### ISSUE THREAD

**Issue by BW15061999** [Taiji-pipeline/Taiji#28]
HI,
when I try to run Sc-ATAC,it generates these error messages below.

And here is my input file and config file
[input.txt](https://github.com/Taiji-pipeline/Taiji/files/9089586/input.txt)
[config.txt](https://github.com/Taiji-pipeline/Taiji/files/9089593/config.txt)

Do you know what cause this error? Thank you!

Best

```
[INFO][07-12 12:45] SCATAC_Pre_Cluster(f197..): Running ...
Read Data
Use jaccard distance
Compute similarity matrix
/home/bruce/Downloads/Softwares/Anaconda/envs/RGT/lib/python3.10/site-packages/sklearn/utils/validation.py:727: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
Traceback (most recent call last):
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/RGT/bin/taiji-utils", line 8, in <module>
    sys.exit(main())
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/RGT/lib/python3.10/site-packages/taiji_utils/__init__.py", line 151, in main
    args.func(args)
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/RGT/lib/python3.10/site-packages/taiji_utils/__init__.py", line 12, in reduce
    spectral(args)
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/RGT/lib/python3.10/site-packages/taiji_utils/Spectral.py", line 38, in spectral
    res = Spectral(mat, n_dim=args.dim, distance=args.distance).coordinates[:, 1:]
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/RGT/lib/python3.10/site-packages/taiji_utils/Spectral.py", line 62, in __init__
    self.normalizer = Normalizer(jm, self.coverage)
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/RGT/lib/python3.10/site-packages/taiji_utils/Spectral.py", line 101, in __init__
    self.model = LinearRegression().fit(X, y)
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/RGT/lib/python3.10/site-packages/sklearn/linear_model/_base.py", line 684, in fit
    X, y = self._validate_data(
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/RGT/lib/python3.10/site-packages/sklearn/base.py", line 596, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/RGT/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1074, in check_X_y
    X = check_array(
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/RGT/lib/python3.10/site-packages/sklearn/utils/validation.py", line 909, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required by LinearRegression.
[ERROR][07-12 12:46] SCATAC_Pre_Cluster(f197..) Failed: 
Ran commands: 
taiji-utils reduce /tmp/tmp_dir_-4fd2acb8b9d4c38f/Apex_rep1_filt.mat.gz /tmp/tmp_dir_-4fd2acb8b9d4c38f/Apex_rep1_spectral.tsv.gz
which taiji-utils

Exception: error running: taiji-utils reduce /tmp/tmp_dir_-4fd2acb8b9d4c38f/Apex_rep1_filt.mat.gz /tmp/tmp_dir_-4fd2acb8b9d4c38f/Apex_rep1_spectral.tsv.gz
exit status: 1
stderr: /home/bruce/Downloads/Softwares/Anaconda/envs/RGT/lib/python3.10/site-packages/sklearn/utils/validation.py:727: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
Traceback (most recent call last):
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/RGT/bin/taiji-utils", line 8, in <module>
    sys.exit(main())
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/RGT/lib/python3.10/site-packages/taiji_utils/__init__.py", line 151, in main
    args.func(args)
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/RGT/lib/python3.10/site-packages/taiji_utils/__init__.py", line 12, in reduce
    spectral(args)
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/RGT/lib/python3.10/site-packages/taiji_utils/Spectral.py", line 38, in spectral
    res = Spectral(mat, n_dim=args.dim, distance=args.distance).coordinates[:, 1:]
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/RGT/lib/python3.10/site-packages/taiji_utils/Spectral.py", line 62, in __init__
    self.normalizer = Normalizer(jm, self.coverage)
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/RGT/lib/python3.10/site-packages/taiji_utils/Spectral.py", line 101, in __init__
    self.model = LinearRegression().fit(X, y)
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/RGT/lib/python3.10/site-packages/sklearn/linear_model/_base.py", line 684, in fit
    X, y = self._validate_data(
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/RGT/lib/python3.10/site-packages/sklearn/base.py", line 596, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/RGT/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1074, in check_X_y
    X = check_array(
  File "/home/bruce/Downloads/Softwares/Anaconda/envs/RGT/lib/python3.10/site-packages/sklearn/utils/validation.py", line 909, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required by LinearRegression.

CallStack (from HasCallStack):
  error, called at src/Control/Workflow/Interpreter/Exec.hs:146:37 in SciFlow-0.8.0-IRKsT2ba9M716PeGlwt2FT:Control.Workflow.Interpreter.Exec
[ERROR][07-12 12:46] Program exits with errors
```

**Comment by kaizhang** [comment]
For single-cell analysis, please use this new package: https://github.com/kaizhang/SnapATAC2

**Comment by BW15061999** [comment]
Thank you! I will try that one
